#!/bin/bash

# Autobuild the Image on Docker Hub with advanced options and buildx for multiarch images
# read more: https://github.com/Tob1asDocker/dockerhubhooksexample

# '--push' shorthand for '--output=type=registry'

set -ex

echo "### RUN build START: using buildx ###"
echo "Image Name: ${IMAGE_NAME} (${DOCKER_IMAGE}) (Repo: ${DOCKER_REPO}, Tag: ${DOCKER_TAG})"
echo "Dockerfile Path/Name: ${DOCKERFILE_PATH}"
BUILDPLATFORM="${BUILDPLATFORM:-"linux/amd64,linux/arm64"}"
echo "Architectures=${BUILDPLATFORM}"

echo "Starting registry"

# Start the local registry
docker run -d -p 127.0.0.1:5000:5000 --rm --name registry registry:2

# Build
# DEP 2/29/24: Pushing to the local registry can fail for PR from a forked repo.
# The original script I copied does the push to docker hub here, and makes
# the push script a no-op.  This is not ideal, but harmless with the 'this' tag.
#
# Unfortunately, when someone creates a PR from a forked repo, this
# push fails with a credential issue.  Probably a good idea for
# security, but also causes the build test to fail.
#
# I tried pushing to a repo on localhost, but this also fails for
# strange reasons (at least as of today).
# 
# Fortunately, for some reason the build test works if we bounce through a file
# (awesome.img).  
#
# If anyone wants to change this in the future, be aware during
# testing.  The old behavior (pushing directly to docker hub) works
# just fine on a PR from a local branch.

docker buildx build --build-arg BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')" --build-arg VCS_REF="$(git rev-parse --short HEAD)" --tag "${IMAGE_NAME}" --platform "${BUILDPLATFORM}" --file "${DOCKERFILE_PATH}" -o type=docker,dest=awesome.img .

# Load the image into the local registry
docker load --input awesome.img

# Tag the local version so that we can push in the push script, should we choose
#docker tag ${IMAGE_NAME} ${OLD_IMAGE_NAME}

# Confirm the build really was both archs
#docker buildx inspect

echo "### RUN build END"
