#!/bin/bash

# If use 'docker buildx build' then disable the push of 'docker build', because the push has already been done and fails here.

set -ex

echo "### RUN push START ###"
echo "Image Name: ${IMAGE_NAME} (Repo: ${DOCKER_REPO}, Tag: ${DOCKER_TAG})"

docker image push ${DOCKER_IMAGE}

echo "### RUN push START ###"
