#!/bin/bash

# If use 'docker buildx build' then disable the push of 'docker build', because the push has already been done and fails here.

set -ex

echo "### RUN build and push START: using buildx ###"
echo "Image Name: ${IMAGE_NAME} (Repo: ${DOCKER_REPO}, Tag: ${DOCKER_TAG})"
echo "Dockerfile Path/Name: ${DOCKERFILE_PATH}"
BUILDPLATFORM="${BUILDPLATFORM:-"linux/amd64,linux/arm64"}"
echo "Architectures=${BUILDPLATFORM}"

# Rebuild and push.  Maybe something will be cached, but rebuilding is
# the only reliable way to navigate permissions in the docker hub autobuild
# environment
docker buildx build --build-arg BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')" --build-arg VCS_REF="$(git rev-parse --short HEAD)" --tag "${IMAGE_NAME}" --platform "${BUILDPLATFORM}" --file "${DOCKERFILE_PATH}" --push .
